name: Check latest Lens version

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Access Token
        shell: bash
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_INSTALL_ID: ${{ secrets.APP_INSTALL_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          GAIT: github-app-installation-token
          GAIT_VERSION: 1.2.0
        run: |
          wget -nv -O ${GAIT}.zip https://github.com/gagoar/${GAIT}/releases/download/v${GAIT_VERSION}/linux.zip
          unzip ${GAIT}.zip
          echo $APP_PRIVATE_KEY > APP_PRIVATE_KEY
          export ACCESS_TOKEN=`./cli-linux \
            --appId $APP_ID \
            --installationId $APP_INSTALL_ID \
            --privateKeyLocation APP_PRIVATE_KEY`
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ env.ACCESS_TOKEN }}
      - name: Get the latest version of Lens
        run: |
          curl -s https://api.github.com/repos/lensapp/lens/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name[1:]' > version
          echo "LENS_VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: ${{ env.LENS_VERSION }}'
